#!/usr/bin/env bash
set -euo pipefail

# install.sh
#
# One-shot installer intended for: curl ... | sudo bash
#
# - Downloads latest GitHub Release asset (linux-x64)
# - Verifies sha256
# - Installs:
#     /usr/local/bin/discord-indexer
#     /usr/local/bin/discord-indexer-search
# - If an OpenClaw config is found, reads channels.discord.token and writes
#   /etc/discord-indexer/indexer.env (0600) without printing the token.

REPO="${REPO:-patrick-slimelab/discord-indexer-dotnet}"
VERSION="${VERSION:-latest}" # latest or vX.Y.Z
PREFIX="${PREFIX:-/usr/local/bin}"

ASSET_TGZ="discord-indexer-linux-x64.tar.gz"
ASSET_SHA="discord-indexer-linux-x64.sha256"

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: missing required command: $1" >&2
    exit 1
  }
}

need curl
need tar
need sha256sum

if [[ "$(id -u)" -ne 0 ]]; then
  echo "ERROR: run as root (use: curl ... | sudo bash)" >&2
  exit 1
fi

# Resolve the invoking user's home dir (important because we're usually root via sudo)
INVOKER="${SUDO_USER:-}"
if [[ -z "$INVOKER" ]]; then
  INVOKER="$(logname 2>/dev/null || true)"
fi
if [[ -z "$INVOKER" ]]; then
  INVOKER="root"
fi

INVOKER_HOME="$(getent passwd "$INVOKER" | cut -d: -f6)"
if [[ -z "$INVOKER_HOME" ]]; then
  INVOKER_HOME="/root"
fi

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

resolve_latest_tag() {
  curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
    | sed -n 's/.*"tag_name" *: *"\([^"]*\)".*/\1/p' \
    | head -n1
}

TAG="$VERSION"
if [[ "$VERSION" == "latest" ]]; then
  echo "[install] Resolving latest release for $REPO"
  TAG="$(resolve_latest_tag)"
  if [[ -z "$TAG" ]]; then
    echo "ERROR: could not resolve latest release tag" >&2
    exit 1
  fi
fi

BASE_URL="https://github.com/${REPO}/releases/download/${TAG}"

echo "[install] Downloading ${ASSET_TGZ} (${TAG})"
curl -fsSL -o "$TMP/$ASSET_TGZ" "$BASE_URL/$ASSET_TGZ"
curl -fsSL -o "$TMP/$ASSET_SHA" "$BASE_URL/$ASSET_SHA"

cd "$TMP"

echo "[install] Extracting"
tar -xzf "$ASSET_TGZ"

echo "[install] Verifying checksums"
sha256sum -c "$ASSET_SHA"

install -d "$PREFIX"
install -m 0755 "$TMP/discord-indexer" "$PREFIX/discord-indexer"
install -m 0755 "$TMP/discord-indexer-search" "$PREFIX/discord-indexer-search"

echo "[install] Installed binaries to $PREFIX"

# --- OpenClaw token detection ---
read_discord_token_from_openclaw() {
  # Try standard OpenClaw state dirs
  local home="$1"
  local candidates=(
    "$home/.openclaw/openclaw.json"
    "$home/.moltbot/openclaw.json"
    "$home/.clawdbot/openclaw.json"
  )

  for cfg in "${candidates[@]}"; do
    if [[ -f "$cfg" ]]; then
      if command -v jq >/dev/null 2>&1; then
        local tok
        tok="$(jq -r '.channels.discord.token // empty' "$cfg" 2>/dev/null || true)"
        if [[ -n "$tok" && "$tok" != "null" ]]; then
          echo "$tok"
          return 0
        fi
      fi
    fi
  done

  return 1
}

TOKEN=""
# Prefer jq, but fall back to python3 for JSON parsing (common on Linux)
if command -v jq >/dev/null 2>&1; then
  TOKEN="$(read_discord_token_from_openclaw "$INVOKER_HOME" || true)"
else
  # python3 fallback
  if command -v python3 >/dev/null 2>&1; then
    for cfg in \
      "$INVOKER_HOME/.openclaw/openclaw.json" \
      "$INVOKER_HOME/.moltbot/openclaw.json" \
      "$INVOKER_HOME/.clawdbot/openclaw.json"; do
      if [[ -f "$cfg" ]]; then
        TOKEN="$(python3 - <<PY 2>/dev/null || true
import json
p = r'''$cfg'''
with open(p,'r',encoding='utf-8') as f:
  data=json.load(f)
print((data.get('channels',{}) or {}).get('discord',{}).get('token','') or '')
PY
)"
        if [[ -n "$TOKEN" ]]; then
          break
        fi
      fi
    done
  else
    echo "[install] NOTE: neither jq nor python3 found; skipping OpenClaw token detection" >&2
  fi
fi

# --- Write env file ---
ENV_DIR="/etc/discord-indexer"
ENV_FILE="$ENV_DIR/indexer.env"

install -d -m 0755 "$ENV_DIR"

umask 077

if [[ ! -f "$ENV_FILE" ]]; then
  {
    echo "# discord-indexer environment (generated by install.sh)"
    echo "MONGODB_URI=\"mongodb://127.0.0.1:27017\""
    echo "MONGODB_DB=\"discord_index\""
    echo "DISCORD_GUILD_IDS=\"\""
    echo "DISCORD_INTENTS=\"4609\""
    echo "INDEXER_BACKFILL_WORKERS=\"1\""
    echo "INDEXER_BACKFILL_REQUEST_DELAY_MS=\"250\""
    if [[ -n "$TOKEN" ]]; then
      echo "DISCORD_BOT_TOKEN=\"$TOKEN\""
      echo "# token source: OpenClaw config (channels.discord.token)"
    else
      echo "# DISCORD_BOT_TOKEN not set (no OpenClaw config detected)."
      echo "# Add it here before running the indexer."
    fi
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "[install] Wrote $ENV_FILE (0600)"
else
  # If env exists and token is missing, and we detected a token from OpenClaw, patch it in.
  if [[ -n "$TOKEN" ]] && ! grep -q '^DISCORD_BOT_TOKEN=' "$ENV_FILE"; then
    echo "[install] Updating existing $ENV_FILE with DISCORD_BOT_TOKEN from OpenClaw (no token printed)"
    printf '\nDISCORD_BOT_TOKEN="%s"\n# token source: OpenClaw config (channels.discord.token)\n' "$TOKEN" >> "$ENV_FILE"
    chmod 600 "$ENV_FILE"
  else
    echo "[install] $ENV_FILE already exists; leaving it unchanged"
  fi
fi

cat <<EOF

[install] Next steps:
- Edit $ENV_FILE as needed.
- Run the indexer:
    set -a; source $ENV_FILE; set +a; discord-indexer

EOF
